/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package xyz.ludoviko.administrado

import tornadofx.launch
import xyz.ludoviko.administrado.views.MainView

class App : tornadofx.App(MainView::class)

fun main(args: Array<String>) {
    launch<App>(args)
}
